version: '2'

services:
  ros2_control:
    build: .
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspaces
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:$XAUTHORITY
      - ./limits.conf:/etc/security/limits.conf
      - ~/.gitconfig:/etc/gitconfig:ro
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    user: $UID:$UID
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
